name: Setup & Build release containers
on:
  push:
    branches:
      - 'release/**'
  pull_request:
    branches:
      - 'release/**'

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python-version: ['3.8']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup env
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
    - name: Build docker image
      run: |
        make docker
    - name: Read VERSION file
      id: getversion
      run: echo "::set-output name=version::$(cat CalmVersion)"
    - name: Execute container
      uses: addnab/docker-run-action@v3
      with:
        image: ntnx/calm-dsl
        run: calm
    - name: Publish docker image to jfrog-artifactory
      if: ${{ github.repository == 'nutanix/calm-dsl' && matrix.python-version == '3.8'}}
      run: |
        docker login ${{ secrets.JFROG_REGISTRY }} -u ${{ secrets.JFROG_USERNAME }} -p ${{ secrets.JFROG_PASSWORD }}
        docker tag ntnx/calm-dsl:latest ${{ secrets.JFROG_REGISTRY }}/calm-dsl/calm-dsl:v${{ steps.getversion.outputs.version }}
        docker push ${{ secrets.JFROG_REGISTRY }}/calm-dsl/calm-dsl:v${{ steps.getversion.outputs.version }}
